n = input('Digite algo ai: ')
print('Todos o caracteres são letras?', n.isalpha())
print('todos os caractesres são letras ou números?', n.isalnum())
print('Todos os caracteres são números decimais?', n.isdecimal())
print('Todos os caracteres são dígitos? ', n.isdigit())
print('Todos os caracteres são números? ', n.isnumeric())
print('Todos os caracteres estão em minúscula? ', n.islower())
print('Todos os caracteres estão em maiúscula? ', n.isupper())
print('String está em formato de titulo? ', n.istitle())
print('Todos os caracteres são espaços? ', n.isspace())
print('Todos os caracteres são imprimíveis?', n.isprintable())
print('A String é um indentificador válido em Python? ', n.isidentifier())
print('Todos os caracteres são ASCII? ', n.isascii())